######################################################################
# Automatically generated by qmake (2.01a) Pzt May 14 17:40:24 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += cal.h
SOURCES += cal.cpp main.cpp
